name: Create plots

on:
    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:   
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up environment
              uses: ./

            - name: Run R script
              run: Rscript docs/create-plots.R

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v2
              with:
                token: ${{ secrets.GH_TOKEN }}
                commit-message: Update graphs
                title: Update graphs
                branch: update-graphs