name: Run R script

on:
    workflow_run:
      workflows: ["Set up R environment"]
      types:
        - completed

jobs:
    run:
        runs-on: ubuntu-latest
        steps:   
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run R script
              run: Rscript sample-script.R