name: Run R script

on:
    workflow_dispatch:
      inputs:
        first_run:
          required: true
          type: choice
          default: "FALSE"
          options:
            - "TRUE"
            - "FALSE"
        test:
          required: true
          type: choice
          default: "FALSE"
          options:
            - "TRUE"
            - "FALSE"

jobs:
    run:
        runs-on: ubuntu-latest
        env:
          TEST: ${{ inputs.test || 'FALSE' }}
          FIRST_RUN: ${{ inputs.first_run || 'FALSE' }}
          DSCI_AZ_SAS_DEV: ${{ secrets.DSCI_AZ_SAS_DEV }}
          DSCI_AZ_KEY_DEV: ${{ secrets.DSCI_AZ_KEY_DEV }}
          DSCI_AZ_ENDPOINT: ${{ secrets.DSCI_AZ_ENDPOINT }}
        steps:   
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up environment
              uses: ocha-dap/hdx-signals-actions@2dfcc5c8796903a01b393b8ebed26d2582f305ff

            - name: Run R script
              run: Rscript sample-script.R