name: Set up R environment

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            RENV_PATHS_ROOT: ~/.cache/R/renv
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Set up R
              uses: r-lib/actions/setup-r@v2
              with:
                r-version: '4.3.3'
        
            - name: Cache packages
              uses: actions/cache@v3
              with:
                path: ${{ env.RENV_PATHS_ROOT }}
                key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
                restore-keys: |
                  ${{ runner.os }}-renv-

            - name: Restore packages
              run: |
                if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
                renv::restore()
              shell: Rscript {0}
